name: Whispah
options:
  bundleIdPrefix: com.whispah
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.35"

packages:
  SwiftWhisper:
    url: https://github.com/exPHAT/SwiftWhisper.git
    from: "1.1.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts.git
    from: "2.0.0"

targets:
  Whispah:
    type: application
    platform: macOS
    sources:
      - Whispah
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.whispah.Whispah
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_FILE: Whispah/Info.plist
        ENABLE_APP_SANDBOX: false
        CODE_SIGN_ENTITLEMENTS: Whispah/Whispah.entitlements
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: SwiftWhisper
      - package: KeyboardShortcuts
    entitlements:
      path: Whispah/Whispah.entitlements
      properties:
        com.apple.security.device.audio-input: true
